# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  enabled: true
  host: localhost
  port: 8080

development:
  <<: *default

test:
  <<: *default
  enabled: false
  port: 3030

production:
  <<: *default
  enabled: false
